# Generated by Django 4.2.2 on 2023-07-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteflow', '0002_booking_table_donation_table_festival_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_table',
            name='date',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking_table',
            name='pincode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
