# Generated by Django 4.2.2 on 2023-07-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteflow', '0003_booking_table_date_booking_table_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_table',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking_table',
            name='nakshatra',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking_table',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
