# Generated by Django 4.2.2 on 2023-07-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteflow', '0004_booking_table_payment_alter_booking_table_nakshatra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_table',
            name='razorpay_orderid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
