# Generated by Django 4.2.2 on 2023-07-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteflow', '0005_booking_table_razorpay_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_table',
            name='booking_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
